
CREATE TABLE movie_cast (
	movie_id 	INT,
	role 		VARCHAR(50),
	character 	VARCHAR(70),
	actor 		VARCHAR(70)
);

INSERT INTO movie_cast VALUES (1001, 'Bond Girl', 'Honey Ryder', 'Ursula Andress');
INSERT INTO movie_cast VALUES (1001, 'Bond Girl', 'Sylvia Trench', 'Eunice Gayson');
INSERT INTO movie_cast VALUES (1001, 'Bond Girl', 'Miss Taro', 'Zena Marshall');
INSERT INTO movie_cast VALUES (1001, 'Villain', 'Dr. No', 'Joseph Wiseman');
INSERT INTO movie_cast VALUES (1001, 'Counterpart', 'Felix Leiter', 'Jack Lord');
INSERT INTO movie_cast VALUES (1001, 'Counterpart', 'Quarrel', 'John Kitzmuller');
INSERT INTO movie_cast VALUES (1002, 'Bond Girl', 'Tatiana "Tanya" Romanova', 'Daniela Bianchi');
INSERT INTO movie_cast VALUES (1002, 'Bond Girl', 'Vida', 'Aliza Gur');
INSERT INTO movie_cast VALUES (1002, 'Bond Girl', 'Zora', 'Martine Beswick');
INSERT INTO movie_cast VALUES (1002, 'Bond Girl', 'Sylvia Trench', 'Eunice Gayson');
INSERT INTO movie_cast VALUES (1002, 'Villain', 'Donald Grant', 'Robert Shaw');
INSERT INTO movie_cast VALUES (1002, 'Villain', 'Colonel Rosa Klebb / "No. 3"', 'Lotte Lenya');
INSERT INTO movie_cast VALUES (1002, 'Villain', 'Kronsteen / "No. 5"', 'Vladek Sheybal');
INSERT INTO movie_cast VALUES (1002, 'Counterpart', 'Karim Bey', 'Pedro Armendariz');
INSERT INTO movie_cast VALUES (1003, 'Bond Girl', 'Pussy Galore', 'Honor Blackman');
INSERT INTO movie_cast VALUES (1003, 'Bond Girl', 'Jill Masterson', 'Shirley Eaton');
INSERT INTO movie_cast VALUES (1003, 'Bond Girl', 'Tilly Masterson', 'Tania Mallet');
INSERT INTO movie_cast VALUES (1003, 'Villain', 'Auric Goldfinger', 'Gert Frobe');
INSERT INTO movie_cast VALUES (1003, 'Villain', 'Oddjob', 'Harold Sakata');
INSERT INTO movie_cast VALUES (1003, 'Villain', 'Kisch', 'Michael Mellinger');
INSERT INTO movie_cast VALUES (1003, 'Counterpart', 'Felix Leiter', 'Cec Linder');
INSERT INTO movie_cast VALUES (1004, 'Bond Girl', 'Domonique "Domino" Derval', 'Claudine Auger');
INSERT INTO movie_cast VALUES (1004, 'Bond Girl', 'Fiona Volpe', 'Luciana Paluzzi');
INSERT INTO movie_cast VALUES (1004, 'Bond Girl', 'Paula Catlin', 'Martine Beswick');
INSERT INTO movie_cast VALUES (1004, 'Bond Girl', 'Patricia Fearing', 'Molly Peters');
INSERT INTO movie_cast VALUES (1004, 'Villain', 'Amelio Largo / "No. 2"', 'Adolfo Cali');
INSERT INTO movie_cast VALUES (1004, 'Villain', 'Vargas', 'Philip Locke');
INSERT INTO movie_cast VALUES (1004, 'Counterpart', 'Felix Leiter', 'Rik Van Nutter');
INSERT INTO movie_cast VALUES (1005, 'Bond Girl', 'Aki', 'Akiko Wakabayashi');
INSERT INTO movie_cast VALUES (1005, 'Bond Girl', 'Kissy', 'Mie Hama');
INSERT INTO movie_cast VALUES (1005, 'Bond Girl', 'Helga Brandt', 'Karin Dor');
INSERT INTO movie_cast VALUES (1005, 'Bond Girl', 'Ling', 'Tsaj Chin');
INSERT INTO movie_cast VALUES (1005, 'Villain', 'Ernest Blofeld', 'Donald Pleasence');
INSERT INTO movie_cast VALUES (1005, 'Villain', 'Osato', 'Teru Shimada');
INSERT INTO movie_cast VALUES (1005, 'Counterpart', 'Tiger Tanaka', 'Tersuro Tamba');
INSERT INTO movie_cast VALUES (1005, 'Counterpart', 'Henderson', 'Charles Gray');
INSERT INTO movie_cast VALUES (1006, 'Bond Girl', 'Teresa Draco Bond', 'Diana Riggs');
INSERT INTO movie_cast VALUES (1006, 'Bond Girl', 'Ruby Bartlett', 'Angela Scoular');
INSERT INTO movie_cast VALUES (1006, 'Bond Girl', 'Nancy', 'Catherine Von Schell');
INSERT INTO movie_cast VALUES (1006, 'Villain', 'Ernest Blofeld', 'Telly Savalas');
INSERT INTO movie_cast VALUES (1006, 'Villain', 'Irma Bunt', 'Ilse Steppat');
INSERT INTO movie_cast VALUES (1006, 'Counterpart', 'Marcos Draco', 'Gabriele Farzetti');
INSERT INTO movie_cast VALUES (1007, 'Bond Girl', 'Tiffany Case', 'Jill St. John');
INSERT INTO movie_cast VALUES (1007, 'Bond Girl', 'Plenty O''Toole', 'Lana Wood');
INSERT INTO movie_cast VALUES (1007, 'Bond Girl', 'Bambi', 'Lola Larson');
INSERT INTO movie_cast VALUES (1007, 'Bond Girl', 'Thumper', 'Trina Parks');
INSERT INTO movie_cast VALUES (1007, 'Villain', 'Ernest Blofeld', 'Charles Gray');
INSERT INTO movie_cast VALUES (1007, 'Villain', 'Mr. Wint', 'Bruce Glover');
INSERT INTO movie_cast VALUES (1007, 'Villain', 'Mr. Kidd', 'Putter Smith');
INSERT INTO movie_cast VALUES (1007, 'Villain', 'Dr. Metz', 'Joseph Furst');
INSERT INTO movie_cast VALUES (1007, 'Counterpart', 'Felix Leiter', 'Norman Burton');
INSERT INTO movie_cast VALUES (1007, 'Counterpart', 'Willard Whyte', 'Jimmy Dean');
INSERT INTO movie_cast VALUES (1008, 'Bond Girl', 'Solitaire', 'Jane Seymour');
INSERT INTO movie_cast VALUES (1008, 'Bond Girl', 'Rosie Carver', 'Gloria Hendry');
INSERT INTO movie_cast VALUES (1008, 'Villain', 'Kananga / Mr. Big', 'Yaphet Kotto');
INSERT INTO movie_cast VALUES (1008, 'Villain', 'Tee Hee', 'Julius W. Harris');
INSERT INTO movie_cast VALUES (1008, 'Villain', 'Baron Samedi', 'Geoffrey Holder');
INSERT INTO movie_cast VALUES (1008, 'Counterpart', 'Felix Leiter', 'David Hedison');
INSERT INTO movie_cast VALUES (1008, 'Counterpart', 'Quarrel Jr.', 'Roy Stewart');
INSERT INTO movie_cast VALUES (1008, 'Counterpart', 'Sheriff J. W. Pepper', 'Clifton James');
INSERT INTO movie_cast VALUES (1009, 'Bond Girl', 'Mary Goodnight', 'Britt Ekland');
INSERT INTO movie_cast VALUES (1009, 'Bond Girl', 'Andrea Anders', 'Maud Adams');
INSERT INTO movie_cast VALUES (1009, 'Bond Girl', 'Chula', 'Chan Yiu Lam');
INSERT INTO movie_cast VALUES (1009, 'Bond Girl', 'Saida', 'Carmen Sautoy');
INSERT INTO movie_cast VALUES (1009, 'Villain', 'Fransisco Scaramanga', 'Christopher Lee');
INSERT INTO movie_cast VALUES (1009, 'Villain', 'Nick Nack', 'Herve Villechaize');
INSERT INTO movie_cast VALUES (1009, 'Villain', 'Hai Fat', 'Richard Loo');
INSERT INTO movie_cast VALUES (1009, 'Counterpart', 'Lt. Hip', 'Soon-Taik Oh');
INSERT INTO movie_cast VALUES (1009, 'Counterpart', 'Sheriff J. W. Pepper', 'Clifton James');
INSERT INTO movie_cast VALUES (1010, 'Bond Girl', 'Agent XXX / Anya Amasova', 'Barbara Bach');
INSERT INTO movie_cast VALUES (1010, 'Bond Girl', 'Naomi', 'Caroline Munro');
INSERT INTO movie_cast VALUES (1010, 'Villain', 'Karl Stromberg', 'Curt Jurgens');
INSERT INTO movie_cast VALUES (1010, 'Villain', 'Jaws', 'Richard Kiel');
INSERT INTO movie_cast VALUES (1010, 'Counterpart', 'Captain Benson', 'George Baker');
INSERT INTO movie_cast VALUES (1011, 'Bond Girl', 'Holly Goodhead', 'Lois Chiles');
INSERT INTO movie_cast VALUES (1011, 'Bond Girl', 'Corinne Dufour', 'Corinne Clery');
INSERT INTO movie_cast VALUES (1011, 'Bond Girl', 'Manuela', 'Emily Bolton');
INSERT INTO movie_cast VALUES (1011, 'Villain', 'Hugo Drax', 'Michael Lonsdale');
INSERT INTO movie_cast VALUES (1011, 'Villain', 'Jaws', 'Richard Kiel');
INSERT INTO movie_cast VALUES (1011, 'Villain', 'Chang', 'Toshiro Suga');
INSERT INTO movie_cast VALUES (1012, 'Bond Girl', 'Melina Havelock', 'Carole Bouquet');
INSERT INTO movie_cast VALUES (1012, 'Bond Girl', 'Bibi Dahl', 'Lynn-Holly Johnson');
INSERT INTO movie_cast VALUES (1012, 'Bond Girl', 'Countess Lisi VonShlout', 'Cassandra Harris');
INSERT INTO movie_cast VALUES (1012, 'Villain', 'Ares Kristatos', 'Julian Glover');
INSERT INTO movie_cast VALUES (1012, 'Villain', 'Amele Leopold Locque', 'Michael Gothard');
INSERT INTO movie_cast VALUES (1012, 'Villain', 'Erik Kriegier', 'John Wyman');
INSERT INTO movie_cast VALUES (1012, 'Counterpart', 'Miles Colombo / The Dove', 'Topol');
INSERT INTO movie_cast VALUES (1012, 'Counterpart', 'Luigi Ferrara', 'John Moreno');
INSERT INTO movie_cast VALUES (1013, 'Bond Girl', 'Octopussy', 'Maud Adams');
INSERT INTO movie_cast VALUES (1013, 'Bond Girl', 'Magda', 'Kristina Wayborn');
INSERT INTO movie_cast VALUES (1013, 'Villain', 'Kamal', 'Louis Jourdan');
INSERT INTO movie_cast VALUES (1013, 'Villain', 'Gobinda', 'Kabir Bedi');
INSERT INTO movie_cast VALUES (1013, 'Villain', 'General Orlov', 'Steven Berkoff');
INSERT INTO movie_cast VALUES (1013, 'Villain', 'Mishka', 'David Meyer');
INSERT INTO movie_cast VALUES (1013, 'Villain', 'Grishka', 'Anthony Meyer');
INSERT INTO movie_cast VALUES (1013, 'Counterpart', 'Vijay', 'Vijay Amritraj');
INSERT INTO movie_cast VALUES (1014, 'Bond Girl', 'Domino Petachi', 'Kim Basinger');
INSERT INTO movie_cast VALUES (1014, 'Bond Girl', 'Fatima Blush', 'Barbara Carrera');
INSERT INTO movie_cast VALUES (1014, 'Bond Girl', 'Nicole', 'Saskia Cohen Tanugi');
INSERT INTO movie_cast VALUES (1014, 'Villain', 'Maxamillion Largo', 'Klaus Brandauer');
INSERT INTO movie_cast VALUES (1014, 'Villain', 'Ernest Blofeld', 'Max Von Sydow');
INSERT INTO movie_cast VALUES (1014, 'Counterpart', 'Felix Leiter', 'Bernie Casey');
INSERT INTO movie_cast VALUES (1014, 'Counterpart', 'Nigel Small-Fawcett', 'Rowan Atkinson');
INSERT INTO movie_cast VALUES (1015, 'Bond Girl', 'Stacey Sutton', 'Tanya Roberts');
INSERT INTO movie_cast VALUES (1015, 'Bond Girl', 'May Day', 'Grace Jones');
INSERT INTO movie_cast VALUES (1015, 'Bond Girl', 'Jenny Flex', 'Alison Doody');
INSERT INTO movie_cast VALUES (1015, 'Bond Girl', 'Pola Ivanova', 'Fiona Fullerton');
INSERT INTO movie_cast VALUES (1015, 'Bond Girl', 'Kimberley Jones', 'Mary Stavin');
INSERT INTO movie_cast VALUES (1015, 'Villain', 'Max Zorin', 'Christopher Walken');
INSERT INTO movie_cast VALUES (1015, 'Villain', 'Scarpine', 'Patrick Bauchau');
INSERT INTO movie_cast VALUES (1015, 'Villain', 'Dr. Carl Mortner', 'Willoughby Gray');
INSERT INTO movie_cast VALUES (1015, 'Counterpart', 'Sir Godfried Tibbett', 'Patrick Macnee');
INSERT INTO movie_cast VALUES (1015, 'Counterpart', 'Chuck Lee', 'David Yip');
INSERT INTO movie_cast VALUES (1016, 'Bond Girl', 'Kara Milovy', 'Maryam d''Abo');
INSERT INTO movie_cast VALUES (1016, 'Bond Girl', 'Rubavitch', 'Virginia Hey');
INSERT INTO movie_cast VALUES (1016, 'Villain', 'General Georgi Koskov', 'Jeroen Krabbe');
INSERT INTO movie_cast VALUES (1016, 'Villain', 'Brad Whitaker', 'Joe Don Baker');
INSERT INTO movie_cast VALUES (1016, 'Villain', 'Necros', 'Andreas Wisniewski');
INSERT INTO movie_cast VALUES (1016, 'Counterpart', 'General Leonid Pushkin', 'John Rhys-Davies');
INSERT INTO movie_cast VALUES (1016, 'Counterpart', 'Kamran Shah', 'Art Malik');
INSERT INTO movie_cast VALUES (1016, 'Counterpart', 'Felix Leiter', 'John Terry');
INSERT INTO movie_cast VALUES (1016, 'Counterpart', 'Saunders', 'Thomas Wheatley');
INSERT INTO movie_cast VALUES (1017, 'Bond Girl', 'Pam Bouvier', 'Carey Lowell');
INSERT INTO movie_cast VALUES (1017, 'Bond Girl', 'Lupe Lamora', 'Talisa Soto');
INSERT INTO movie_cast VALUES (1017, 'Bond Girl', 'Leti', 'Diana Lee-Hsu');
INSERT INTO movie_cast VALUES (1017, 'Bond Girl', 'Della Churchill-Leiter', 'Priscilla Barnes');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Franz Sanchez', 'Robert Davi');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Milton Krest', 'Anthony Zerbe');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Dario', 'Benicio Del Toro');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Truman Lodge', 'Anthony Starke');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Helier', 'Don Stroud');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Professor Joe Butcher', 'Wayne Newton');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'Killfor', 'Everett McGill');
INSERT INTO movie_cast VALUES (1017, 'Villain', 'President Hector Lopez', 'Pedro Armendariz Jr.');
INSERT INTO movie_cast VALUES (1017, 'Counterpart', 'Felix Leiter', 'David Hedison');
INSERT INTO movie_cast VALUES (1017, 'Counterpart', 'Sharky', 'Frank McRae');
INSERT INTO movie_cast VALUES (1018, 'Bond Girl', 'Natalia Nasanoliov', 'Izabella Scorupco');
INSERT INTO movie_cast VALUES (1018, 'Bond Girl', 'Xenia Onatopp', 'Famke Janssen');
INSERT INTO movie_cast VALUES (1018, 'Bond Girl', 'Inna', 'Minnie Driver');
INSERT INTO movie_cast VALUES (1018, 'Bond Girl', 'Caroline', 'Serina Gordon');
INSERT INTO movie_cast VALUES (1018, 'Villain', 'Agent 006 / Alec Trevelyam', 'Sean Bean');
INSERT INTO movie_cast VALUES (1018, 'Villain', 'Colonel Alcaldi Ourumov', 'Gottfried John');
INSERT INTO movie_cast VALUES (1018, 'Villain', 'Boris Grishenko', 'Alan Cumming');
INSERT INTO movie_cast VALUES (1018, 'Counterpart', 'Jack Waide', 'Joe Don Baker');
INSERT INTO movie_cast VALUES (1018, 'Counterpart', 'Valentin Zukovsky', 'Robbie Coltrane');
INSERT INTO movie_cast VALUES (1019, 'Bond Girl', 'Wai Lin', 'Michelle Yeoh');
INSERT INTO movie_cast VALUES (1019, 'Bond Girl', 'Paris Carver', 'Terri Hatcher');
INSERT INTO movie_cast VALUES (1019, 'Bond Girl', 'Professor Inga Bergstrom', 'Cecilie Thomson');
INSERT INTO movie_cast VALUES (1019, 'Bond Girl', 'PR Lady', 'Daphne Deckers');
INSERT INTO movie_cast VALUES (1019, 'Villain', 'Elliot Carver', 'Jonathan Pryce');
INSERT INTO movie_cast VALUES (1019, 'Villain', 'Stamper', 'Gotz Otto');
INSERT INTO movie_cast VALUES (1019, 'Villain', 'Henry Gupta', 'Ricky Jay');
INSERT INTO movie_cast VALUES (1019, 'Villain', 'Dr. Kaufman', 'Vincent Schavelli');
INSERT INTO movie_cast VALUES (1019, 'Counterpart', 'Jack Waide', 'Joe Don Baker');
INSERT INTO movie_cast VALUES (1020, 'Bond Girl', 'Christmas Jones', 'Denise Richards');
INSERT INTO movie_cast VALUES (1020, 'Bond Girl', 'Electra King', 'Sophie Marceau');
INSERT INTO movie_cast VALUES (1020, 'Bond Girl', 'Dr. Molly Warmflash', 'Serena Scott Thomas');
INSERT INTO movie_cast VALUES (1020, 'Villain', 'Victor Socast / Renard', 'Robert Carlyle');
INSERT INTO movie_cast VALUES (1020, 'Counterpart', 'Valentin Zukovsky', 'Robbie Coltrane');
INSERT INTO movie_cast VALUES (1021, 'Bond Girl', 'Jinx', 'Halle Berry');
INSERT INTO movie_cast VALUES (1021, 'Bond Girl', 'Miranda Frost', 'Rosamund Pike');
INSERT INTO movie_cast VALUES (1021, 'Bond Girl', 'Versi', 'Madonna');
INSERT INTO movie_cast VALUES (1021, 'Villain', 'Gustav Graves', 'Toby Stevens');
INSERT INTO movie_cast VALUES (1021, 'Villain', 'Zao', 'Rick Yune');
INSERT INTO movie_cast VALUES (1021, 'Villain', 'Colonel Moon', 'Will Yun Lee');
INSERT INTO movie_cast VALUES (1021, 'Counterpart', 'Falco', 'Michael Madson');
INSERT INTO movie_cast VALUES (1021, 'Counterpart', 'Raoul', 'Emilio Echevarria');
INSERT INTO movie_cast VALUES (1022, 'Bond Girl', 'Vesper Lynd', 'Eva Green');
INSERT INTO movie_cast VALUES (1022, 'Bond Girl', 'Solange', 'Caterina Murino');
INSERT INTO movie_cast VALUES (1022, 'Bond Girl', 'Valenka', 'Ivana Milicevic');
INSERT INTO movie_cast VALUES (1022, 'Villain', 'Le Chiffre', 'Mads Mikkelsen');
INSERT INTO movie_cast VALUES (1022, 'Villain', 'Alex Dimitrios', 'Simon Abkarian');
INSERT INTO movie_cast VALUES (1022, 'Villain', 'Mr. White', 'Jesper Christensen');
INSERT INTO movie_cast VALUES (1022, 'Villain', 'Steven Obanno', 'Isaach De Bankolé');
INSERT INTO movie_cast VALUES (1022, 'Villain', 'Mollaka', 'Sebastien Foucan');
INSERT INTO movie_cast VALUES (1022, 'Counterpart', 'Felix Leiter', 'Jeffrey Wright');
INSERT INTO movie_cast VALUES (1022, 'Counterpart', 'Rene Mathis', 'Giancarlo Giannini');
INSERT INTO movie_cast VALUES (1023, 'Bond Girl', 'Camille Rivera', 'Olga Kurylenko');
INSERT INTO movie_cast VALUES (1023, 'Bond Girl', 'Strawberry Fields', 'Gemma Arterton');
INSERT INTO movie_cast VALUES (1023, 'Villain', 'Dominic Greene', 'Mathieu Amalric');
INSERT INTO movie_cast VALUES (1023, 'Villain', 'General Medrano', 'Joaquin Cosío');
INSERT INTO movie_cast VALUES (1023, 'Villain', 'Elvis', 'Anatole Taubman');
INSERT INTO movie_cast VALUES (1023, 'Villain', 'Mr. White', 'Jesper Christensen');
INSERT INTO movie_cast VALUES (1023, 'Villain', 'Mr. Slate', 'Neil Jackson');
INSERT INTO movie_cast VALUES (1023, 'Counterpart', 'Felix Leiter', 'Jeffrey Wright');
INSERT INTO movie_cast VALUES (1023, 'Counterpart', 'Rene Mathis', 'Giancarlo Giannini');

