
CREATE TABLE vehicle (
	movie_id INT,
	vehicle VARCHAR(80)
);

INSERT INTO vehicle VALUES (1003, 'Aston Martin DB5');
INSERT INTO vehicle VALUES (1004, 'Aston Martin DB5');
INSERT INTO vehicle VALUES (1004, 'Jet Pack');
INSERT INTO vehicle VALUES (1004, 'Hydrofoil Yacht');
INSERT INTO vehicle VALUES (1004, 'Hydrocarts');
INSERT INTO vehicle VALUES (1005, 'Pod-Capturing Rocket Ship');
INSERT INTO vehicle VALUES (1005, '"Little Nelly" Gyrocopter');
INSERT INTO vehicle VALUES (1007, 'Moon Buggy');
INSERT INTO vehicle VALUES (1007, 'Bubble Boat');
INSERT INTO vehicle VALUES (1007, 'Mini Sub');
INSERT INTO vehicle VALUES (1008, 'Hang Glider');
INSERT INTO vehicle VALUES (1009, 'Queen Victorian Sunken Base');
INSERT INTO vehicle VALUES (1009, 'Flying Jet Car');
INSERT INTO vehicle VALUES (1010, 'Union Jack Parachute Pack');
INSERT INTO vehicle VALUES (1010, 'Lotus Esprey Submarine Car');
INSERT INTO vehicle VALUES (1010, 'Portable Jetski');
INSERT INTO vehicle VALUES (1011, 'Parachute');
INSERT INTO vehicle VALUES (1011, 'Motorized Gondola Hovercraft');
INSERT INTO vehicle VALUES (1011, 'Armored Motor Boat w/ Hang Glider');
INSERT INTO vehicle VALUES (1011, 'Laser Jet Packs');
INSERT INTO vehicle VALUES (1012, 'Remote-Controlled Helicopter');
INSERT INTO vehicle VALUES (1012, 'Lotus Esprey Car');
INSERT INTO vehicle VALUES (1012, 'Spiked Motorcycle');
INSERT INTO vehicle VALUES (1012, 'Neptune Submarine');
INSERT INTO vehicle VALUES (1013, 'Horse Stall Hangar w/ Minijet');
INSERT INTO vehicle VALUES (1013, 'Parachute');
INSERT INTO vehicle VALUES (1013, 'Alligator Submarine');
INSERT INTO vehicle VALUES (1013, 'Union Jack Hot Air Balloon');
INSERT INTO vehicle VALUES (1014, 'Motorcycle');
INSERT INTO vehicle VALUES (1014, 'Hydrobarge');
INSERT INTO vehicle VALUES (1015, 'Iceburg Submarine');
INSERT INTO vehicle VALUES (1015, 'Hidden Parachute');
INSERT INTO vehicle VALUES (1015, 'Blimp');
INSERT INTO vehicle VALUES (1016, 'Parachute w/ Secondary Chute');
INSERT INTO vehicle VALUES (1016, 'Transcontenental Pipeline');
INSERT INTO vehicle VALUES (1016, 'Harrier Jet');
INSERT INTO vehicle VALUES (1016, 'Aston Martin');
INSERT INTO vehicle VALUES (1016, 'Cello Case');
INSERT INTO vehicle VALUES (1016, 'Jeep Drop Parachute');
INSERT INTO vehicle VALUES (1018, 'Bungee Cord');
INSERT INTO vehicle VALUES (1018, 'Aston Martin DB5');
INSERT INTO vehicle VALUES (1018, 'Tiger Stealth Helecopter');
INSERT INTO vehicle VALUES (1018, 'BMW');
INSERT INTO vehicle VALUES (1018, 'Soviet Tank');
INSERT INTO vehicle VALUES (1019, 'BMW 750IL');
INSERT INTO vehicle VALUES (1019, 'HALO Jump Gear');
INSERT INTO vehicle VALUES (1020, 'Q Boat');
INSERT INTO vehicle VALUES (1020, 'Hot Air Balloon');
INSERT INTO vehicle VALUES (1020, 'BMW');
INSERT INTO vehicle VALUES (1020, 'Skis');
INSERT INTO vehicle VALUES (1020, 'Fan Snowmobile');
INSERT INTO vehicle VALUES (1021, 'Hovercraft');
INSERT INTO vehicle VALUES (1021, 'Union Jack Parachute');
INSERT INTO vehicle VALUES (1021, 'Aligator Submarine');
INSERT INTO vehicle VALUES (1021, 'Jet Pack');
INSERT INTO vehicle VALUES (1021, 'Aston Martin Vanish');
INSERT INTO vehicle VALUES (1021, 'Rocket Car');
INSERT INTO vehicle VALUES (1021, 'Snowmobile');
INSERT INTO vehicle VALUES (1021, 'Jaguar');
INSERT INTO vehicle VALUES (1021, 'Switchblade Personal Jet');
INSERT INTO vehicle VALUES (1022, 'Aston Martin DBS');
INSERT INTO vehicle VALUES (1023, 'Aston Martin DBS V12');
INSERT INTO vehicle VALUES (1023, 'Fishing Boat');
INSERT INTO vehicle VALUES (1023, 'Motorcycle');
INSERT INTO vehicle VALUES (1023, 'Range Rover ATV');

