
CREATE TABLE gadget_weapon (
	movie_id INT,
	gadget_weapon VARCHAR(70)
);

INSERT INTO gadget_weapon VALUES (1001, 'Baretta 9mm Handgun');
INSERT INTO gadget_weapon VALUES (1001, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1001, 'Cyanide Cigarette');
INSERT INTO gadget_weapon VALUES (1001, 'Geiger Counter');
INSERT INTO gadget_weapon VALUES (1001, 'Diving Knife');
INSERT INTO gadget_weapon VALUES (1001, 'Radiation Suit');
INSERT INTO gadget_weapon VALUES (1002, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1002, 'Garrote Watch');
INSERT INTO gadget_weapon VALUES (1002, 'Bond Mask');
INSERT INTO gadget_weapon VALUES (1002, 'Machine Guns');
INSERT INTO gadget_weapon VALUES (1002, 'Crossbows');
INSERT INTO gadget_weapon VALUES (1002, 'Flamethrower');
INSERT INTO gadget_weapon VALUES (1002, 'Knives');
INSERT INTO gadget_weapon VALUES (1002, 'Brass Knuckles');
INSERT INTO gadget_weapon VALUES (1002, 'Pager');
INSERT INTO gadget_weapon VALUES (1002, 'Car Phone');
INSERT INTO gadget_weapon VALUES (1002, 'Q Briefcase');
INSERT INTO gadget_weapon VALUES (1002, 'Throwing Knife');
INSERT INTO gadget_weapon VALUES (1002, 'Sniper Rifle');
INSERT INTO gadget_weapon VALUES (1002, 'Tear Gas Talcum Powder');
INSERT INTO gadget_weapon VALUES (1002, 'Lector Decoding Machine');
INSERT INTO gadget_weapon VALUES (1002, 'Bugging Devise');
INSERT INTO gadget_weapon VALUES (1002, 'Phone Bug Detector');
INSERT INTO gadget_weapon VALUES (1002, 'Limpit Mine');
INSERT INTO gadget_weapon VALUES (1002, 'Perescope');
INSERT INTO gadget_weapon VALUES (1002, 'Long-range Radios');
INSERT INTO gadget_weapon VALUES (1002, 'Machete');
INSERT INTO gadget_weapon VALUES (1002, 'One-way Mirror');
INSERT INTO gadget_weapon VALUES (1002, 'Motion Picture Camera');
INSERT INTO gadget_weapon VALUES (1002, 'Camera Audio Recorder');
INSERT INTO gadget_weapon VALUES (1002, 'Gas Mask');
INSERT INTO gadget_weapon VALUES (1002, 'Sleeping Pill');
INSERT INTO gadget_weapon VALUES (1002, 'Flare Gun');
INSERT INTO gadget_weapon VALUES (1002, 'Grenades');
INSERT INTO gadget_weapon VALUES (1002, 'Poison Boot Knife');
INSERT INTO gadget_weapon VALUES (1002, 'Rifle Grenade');
INSERT INTO gadget_weapon VALUES (1003, 'Seagull Camo Scuba Gear');
INSERT INTO gadget_weapon VALUES (1003, 'Grappling Gun');
INSERT INTO gadget_weapon VALUES (1003, 'Plastique Belt w/ Timer');
INSERT INTO gadget_weapon VALUES (1003, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1003, 'Gas Parking Meter');
INSERT INTO gadget_weapon VALUES (1003, 'Bulletproof Vest');
INSERT INTO gadget_weapon VALUES (1003, 'Magnetic Tracking Devise');
INSERT INTO gadget_weapon VALUES (1003, 'Mini-Tracking Devise');
INSERT INTO gadget_weapon VALUES (1003, 'Razor-brimmed Bowler Hat');
INSERT INTO gadget_weapon VALUES (1003, 'Binoculars');
INSERT INTO gadget_weapon VALUES (1003, 'Razor Hidden Compartment');
INSERT INTO gadget_weapon VALUES (1003, 'Shoe Hidden Compartment');
INSERT INTO gadget_weapon VALUES (1004, 'Throwing Knife');
INSERT INTO gadget_weapon VALUES (1004, 'Fireplace Poker');
INSERT INTO gadget_weapon VALUES (1004, 'Pistol');
INSERT INTO gadget_weapon VALUES (1004, 'Cigarette Case Door Opener');
INSERT INTO gadget_weapon VALUES (1004, 'Gas Gun');
INSERT INTO gadget_weapon VALUES (1004, 'Breathing Gear');
INSERT INTO gadget_weapon VALUES (1004, 'Gamma Gas Canister');
INSERT INTO gadget_weapon VALUES (1004, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1004, 'Knife');
INSERT INTO gadget_weapon VALUES (1004, 'Underwater Camoflage Net');
INSERT INTO gadget_weapon VALUES (1004, 'Portrait Map');
INSERT INTO gadget_weapon VALUES (1004, 'Book Tape Recorder');
INSERT INTO gadget_weapon VALUES (1004, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1004, 'Geiger Counter Watch');
INSERT INTO gadget_weapon VALUES (1004, 'Mini Flare Gun');
INSERT INTO gadget_weapon VALUES (1004, 'Mini Rebreather');
INSERT INTO gadget_weapon VALUES (1004, 'Tracking Devise Pill');
INSERT INTO gadget_weapon VALUES (1004, 'Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1004, 'Grenades');
INSERT INTO gadget_weapon VALUES (1004, 'Skeet Rifle');
INSERT INTO gadget_weapon VALUES (1004, 'Cyanide Pill');
INSERT INTO gadget_weapon VALUES (1004, 'Magnifying Bucket');
INSERT INTO gadget_weapon VALUES (1004, 'Rifle');
INSERT INTO gadget_weapon VALUES (1004, 'Geiger Counter Camera');
INSERT INTO gadget_weapon VALUES (1004, 'Underwater Flare');
INSERT INTO gadget_weapon VALUES (1004, 'Oxygen Tank Jet');
INSERT INTO gadget_weapon VALUES (1004, 'Underwater Grenade');
INSERT INTO gadget_weapon VALUES (1004, 'Rescue Balloon');
INSERT INTO gadget_weapon VALUES (1005, 'Folding Wall Bed');
INSERT INTO gadget_weapon VALUES (1005, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1005, 'Coffin Bag');
INSERT INTO gadget_weapon VALUES (1005, 'Torpedo Tube Wet Suit');
INSERT INTO gadget_weapon VALUES (1005, 'Purse Radio');
INSERT INTO gadget_weapon VALUES (1005, 'Knife');
INSERT INTO gadget_weapon VALUES (1005, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1005, 'Samurai Sword');
INSERT INTO gadget_weapon VALUES (1005, 'Safe Cracking Devise');
INSERT INTO gadget_weapon VALUES (1005, 'X-Ray Desk');
INSERT INTO gadget_weapon VALUES (1005, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1005, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1005, 'Two-way Radio');
INSERT INTO gadget_weapon VALUES (1005, 'Helicopter Magnet');
INSERT INTO gadget_weapon VALUES (1005, 'Crobar');
INSERT INTO gadget_weapon VALUES (1005, 'Battlestaff');
INSERT INTO gadget_weapon VALUES (1005, 'Scalpel');
INSERT INTO gadget_weapon VALUES (1005, 'Lipstick Smoke Bomb');
INSERT INTO gadget_weapon VALUES (1005, 'Throwing Stars');
INSERT INTO gadget_weapon VALUES (1005, 'Rocket Gun');
INSERT INTO gadget_weapon VALUES (1005, 'Baby Rocket Cigarette');
INSERT INTO gadget_weapon VALUES (1005, 'Poison String');
INSERT INTO gadget_weapon VALUES (1005, 'Staff Dagger');
INSERT INTO gadget_weapon VALUES (1005, 'Poison Gas');
INSERT INTO gadget_weapon VALUES (1005, 'Suction Cup Pads');
INSERT INTO gadget_weapon VALUES (1005, 'Mini-Explosive');
INSERT INTO gadget_weapon VALUES (1005, 'Hose Ropes');
INSERT INTO gadget_weapon VALUES (1005, 'Wall Mine');
INSERT INTO gadget_weapon VALUES (1005, 'Grenades');
INSERT INTO gadget_weapon VALUES (1006, 'Sniper Rifle');
INSERT INTO gadget_weapon VALUES (1006, 'Pistol');
INSERT INTO gadget_weapon VALUES (1006, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1006, 'Boat Anchor');
INSERT INTO gadget_weapon VALUES (1006, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1006, 'Fishing Knife');
INSERT INTO gadget_weapon VALUES (1006, 'Garrote Watch');
INSERT INTO gadget_weapon VALUES (1006, 'Mini Rebreather');
INSERT INTO gadget_weapon VALUES (1006, 'Skeleton Key');
INSERT INTO gadget_weapon VALUES (1006, 'Safe Cracker / Xerox Case');
INSERT INTO gadget_weapon VALUES (1006, 'Homemade Ruler Lockpick');
INSERT INTO gadget_weapon VALUES (1006, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1006, 'Mountain Climbing Gear');
INSERT INTO gadget_weapon VALUES (1006, 'Billy Club');
INSERT INTO gadget_weapon VALUES (1006, 'Compact Radio');
INSERT INTO gadget_weapon VALUES (1006, 'Biogenetic Perfume');
INSERT INTO gadget_weapon VALUES (1006, 'Infrared Binoculars');
INSERT INTO gadget_weapon VALUES (1006, 'Skis');
INSERT INTO gadget_weapon VALUES (1006, 'Flare Gun');
INSERT INTO gadget_weapon VALUES (1006, 'Flamethrower');
INSERT INTO gadget_weapon VALUES (1006, 'Mini Camera');
INSERT INTO gadget_weapon VALUES (1006, 'Explosives');
INSERT INTO gadget_weapon VALUES (1006, 'Grenade');
INSERT INTO gadget_weapon VALUES (1007, 'Revolver');
INSERT INTO gadget_weapon VALUES (1007, 'Water Gun');
INSERT INTO gadget_weapon VALUES (1007, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1007, 'Steel Rat Trap');
INSERT INTO gadget_weapon VALUES (1007, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1007, 'Scalpels');
INSERT INTO gadget_weapon VALUES (1007, 'Scorpion');
INSERT INTO gadget_weapon VALUES (1007, 'Exaust Pipe Compartment');
INSERT INTO gadget_weapon VALUES (1007, 'Toolbox Bomb');
INSERT INTO gadget_weapon VALUES (1007, 'Bible Hidden Compartment');
INSERT INTO gadget_weapon VALUES (1007, 'Fingerprint Kit and Camera');
INSERT INTO gadget_weapon VALUES (1007, 'Closet Fingerprint Display');
INSERT INTO gadget_weapon VALUES (1007, 'Fake Fingerprints');
INSERT INTO gadget_weapon VALUES (1007, 'Fire Extinguisher');
INSERT INTO gadget_weapon VALUES (1007, 'Line Gun');
INSERT INTO gadget_weapon VALUES (1007, 'Voice Converter Machine');
INSERT INTO gadget_weapon VALUES (1007, 'Sleeping Gas');
INSERT INTO gadget_weapon VALUES (1007, 'Electromagnetic Ring');
INSERT INTO gadget_weapon VALUES (1007, 'Cake Bomb');
INSERT INTO gadget_weapon VALUES (1007, 'Flaming Shishkabob Skewers');
INSERT INTO gadget_weapon VALUES (1007, 'Wine Taster Medallion');
INSERT INTO gadget_weapon VALUES (1008, 'Translation Plug Sonic Bomb');
INSERT INTO gadget_weapon VALUES (1008, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1008, 'Body Grab Coffin');
INSERT INTO gadget_weapon VALUES (1008, 'Magnet Watch w/ Saw Blade');
INSERT INTO gadget_weapon VALUES (1008, 'Car Mirror Gun');
INSERT INTO gadget_weapon VALUES (1008, 'Reel to Reel Tape Player');
INSERT INTO gadget_weapon VALUES (1008, 'Revolving Booth');
INSERT INTO gadget_weapon VALUES (1008, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1008, 'Pistol');
INSERT INTO gadget_weapon VALUES (1008, 'Lighter Radio');
INSERT INTO gadget_weapon VALUES (1008, 'Brush Radio');
INSERT INTO gadget_weapon VALUES (1008, 'Bug Detector');
INSERT INTO gadget_weapon VALUES (1008, 'Bed Bug');
INSERT INTO gadget_weapon VALUES (1008, 'Cologne Flamethrower');
INSERT INTO gadget_weapon VALUES (1008, '.38 Smith and Wesson');
INSERT INTO gadget_weapon VALUES (1008, 'Blow Gun Totem');
INSERT INTO gadget_weapon VALUES (1008, 'Flute Radio');
INSERT INTO gadget_weapon VALUES (1008, 'Camera Totem');
INSERT INTO gadget_weapon VALUES (1008, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1008, 'Machete');
INSERT INTO gadget_weapon VALUES (1008, 'Drop Table');
INSERT INTO gadget_weapon VALUES (1008, 'Shotgun');
INSERT INTO gadget_weapon VALUES (1008, '.357 Magnum');
INSERT INTO gadget_weapon VALUES (1008, 'Spike Bombs');
INSERT INTO gadget_weapon VALUES (1008, 'Compressed Gas Gun');
INSERT INTO gadget_weapon VALUES (1008, 'Fishing Knife');
INSERT INTO gadget_weapon VALUES (1008, 'Wire Cutters');
INSERT INTO gadget_weapon VALUES (1009, '4.2 mm Golden Gun');
INSERT INTO gadget_weapon VALUES (1009, 'Aerosol Can');
INSERT INTO gadget_weapon VALUES (1009, 'Camera Cannon');
INSERT INTO gadget_weapon VALUES (1009, 'Butt-trigger Rifle');
INSERT INTO gadget_weapon VALUES (1009, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1009, 'Fake Third Nipple');
INSERT INTO gadget_weapon VALUES (1009, 'Trident');
INSERT INTO gadget_weapon VALUES (1009, 'Speedboat Propeller Blade');
INSERT INTO gadget_weapon VALUES (1009, 'Walkie-Talkies');
INSERT INTO gadget_weapon VALUES (1009, 'Lockpick Keys');
INSERT INTO gadget_weapon VALUES (1009, 'Tracking Devise');
INSERT INTO gadget_weapon VALUES (1009, 'Knife');
INSERT INTO gadget_weapon VALUES (1010, 'Music Box Communicator');
INSERT INTO gadget_weapon VALUES (1010, 'Teletype Watch');
INSERT INTO gadget_weapon VALUES (1010, 'Walkie-Talkie');
INSERT INTO gadget_weapon VALUES (1010, 'Ski Pole Shotgun');
INSERT INTO gadget_weapon VALUES (1010, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1010, 'Microfilm Viewer Cigar Case');
INSERT INTO gadget_weapon VALUES (1010, 'Cigarette Knockout Gas');
INSERT INTO gadget_weapon VALUES (1010, 'Tray Blade');
INSERT INTO gadget_weapon VALUES (1010, 'Stool Ejection Seat');
INSERT INTO gadget_weapon VALUES (1010, 'Water Pipe Machine Gun');
INSERT INTO gadget_weapon VALUES (1010, 'Oil Slick Gun');
INSERT INTO gadget_weapon VALUES (1010, 'Camel Saddle Blade');
INSERT INTO gadget_weapon VALUES (1010, 'Microfilm Projector');
INSERT INTO gadget_weapon VALUES (1010, 'Hydrojet Missles');
INSERT INTO gadget_weapon VALUES (1010, 'Jet Boat Torpedo');
INSERT INTO gadget_weapon VALUES (1010, 'Hydraulic Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1010, 'Machine Guns');
INSERT INTO gadget_weapon VALUES (1010, 'Grenades');
INSERT INTO gadget_weapon VALUES (1010, 'Flamethrower');
INSERT INTO gadget_weapon VALUES (1010, 'Nuclear Detonator Bomb');
INSERT INTO gadget_weapon VALUES (1010, 'Torpedo Gun');
INSERT INTO gadget_weapon VALUES (1010, 'Electromagnet');
INSERT INTO gadget_weapon VALUES (1011, 'Revolver');
INSERT INTO gadget_weapon VALUES (1011, 'Mirror Video Display');
INSERT INTO gadget_weapon VALUES (1011, 'Dart Gun Watch');
INSERT INTO gadget_weapon VALUES (1011, 'Safe Cracker Cigarette Case');
INSERT INTO gadget_weapon VALUES (1011, 'Mini Camera');
INSERT INTO gadget_weapon VALUES (1011, 'Hunting Rifle');
INSERT INTO gadget_weapon VALUES (1011, 'Sniper Rifle');
INSERT INTO gadget_weapon VALUES (1011, 'Knife Thrower Coffin');
INSERT INTO gadget_weapon VALUES (1011, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1011, 'Lockpick Tools');
INSERT INTO gadget_weapon VALUES (1011, 'Biogenetic Nerve Gas Globes');
INSERT INTO gadget_weapon VALUES (1011, 'Bamboo Sword');
INSERT INTO gadget_weapon VALUES (1011, 'Glass-handled Saber');
INSERT INTO gadget_weapon VALUES (1011, 'Chain');
INSERT INTO gadget_weapon VALUES (1011, 'Hypo Pen');
INSERT INTO gadget_weapon VALUES (1011, 'Dart Gun Diary');
INSERT INTO gadget_weapon VALUES (1011, 'Flamethrower Perfume');
INSERT INTO gadget_weapon VALUES (1011, 'Purse Radio');
INSERT INTO gadget_weapon VALUES (1011, 'Gas Mask');
INSERT INTO gadget_weapon VALUES (1011, 'Knife');
INSERT INTO gadget_weapon VALUES (1011, 'Billy Club');
INSERT INTO gadget_weapon VALUES (1011, 'Scalpel');
INSERT INTO gadget_weapon VALUES (1011, 'Exploding Bolos');
INSERT INTO gadget_weapon VALUES (1011, 'Siesta Machine Gun');
INSERT INTO gadget_weapon VALUES (1011, 'Laser Rifle');
INSERT INTO gadget_weapon VALUES (1011, 'Portrait Video Display');
INSERT INTO gadget_weapon VALUES (1011, 'Plastique Watch');
INSERT INTO gadget_weapon VALUES (1011, 'Tazer Rods');
INSERT INTO gadget_weapon VALUES (1012, 'Mine');
INSERT INTO gadget_weapon VALUES (1012, 'Binoculars');
INSERT INTO gadget_weapon VALUES (1012, 'Pistol');
INSERT INTO gadget_weapon VALUES (1012, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1012, 'Beach Umbrella');
INSERT INTO gadget_weapon VALUES (1012, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1012, 'Sniper Crossbow');
INSERT INTO gadget_weapon VALUES (1012, 'Identigraph');
INSERT INTO gadget_weapon VALUES (1012, 'Cast Club');
INSERT INTO gadget_weapon VALUES (1012, 'Umbrella Claws');
INSERT INTO gadget_weapon VALUES (1012, 'Skier''s Rifle');
INSERT INTO gadget_weapon VALUES (1012, 'Skis');
INSERT INTO gadget_weapon VALUES (1012, 'Ski Pole');
INSERT INTO gadget_weapon VALUES (1012, 'Skates and Hockey Sticks');
INSERT INTO gadget_weapon VALUES (1012, 'Candle Tape Recorder');
INSERT INTO gadget_weapon VALUES (1012, 'Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1012, 'Throwing Knife');
INSERT INTO gadget_weapon VALUES (1012, 'Grenades');
INSERT INTO gadget_weapon VALUES (1012, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1012, 'Deep Sea Diving Gear');
INSERT INTO gadget_weapon VALUES (1012, 'Magnetic Thermite Bomb');
INSERT INTO gadget_weapon VALUES (1012, 'Knife');
INSERT INTO gadget_weapon VALUES (1012, 'Rock Climbing Gear');
INSERT INTO gadget_weapon VALUES (1012, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1012, 'Radio Watch');
INSERT INTO gadget_weapon VALUES (1013, 'Briefcase Compartment');
INSERT INTO gadget_weapon VALUES (1013, 'Time Bomb');
INSERT INTO gadget_weapon VALUES (1013, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1013, 'Throwing Knife');
INSERT INTO gadget_weapon VALUES (1013, 'Shotgun');
INSERT INTO gadget_weapon VALUES (1013, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1013, 'Star Sword');
INSERT INTO gadget_weapon VALUES (1013, 'Machete');
INSERT INTO gadget_weapon VALUES (1013, 'Sabre');
INSERT INTO gadget_weapon VALUES (1013, 'Knife');
INSERT INTO gadget_weapon VALUES (1013, 'Mace');
INSERT INTO gadget_weapon VALUES (1013, 'Electric Rope');
INSERT INTO gadget_weapon VALUES (1013, 'Ram Door');
INSERT INTO gadget_weapon VALUES (1013, 'Faberge Egg Tracking Devise');
INSERT INTO gadget_weapon VALUES (1013, 'Acid Pen');
INSERT INTO gadget_weapon VALUES (1013, 'Radio Directional Watch');
INSERT INTO gadget_weapon VALUES (1013, 'Television Watch');
INSERT INTO gadget_weapon VALUES (1013, 'Rope Sash');
INSERT INTO gadget_weapon VALUES (1013, 'Hunting Rifle');
INSERT INTO gadget_weapon VALUES (1013, 'Yo-Yo Saw');
INSERT INTO gadget_weapon VALUES (1013, 'Binoculars');
INSERT INTO gadget_weapon VALUES (1013, 'Battle Axe');
INSERT INTO gadget_weapon VALUES (1013, 'Garrote');
INSERT INTO gadget_weapon VALUES (1013, 'Dart Gun');
INSERT INTO gadget_weapon VALUES (1013, 'Blow Torch');
INSERT INTO gadget_weapon VALUES (1013, 'Bolo Rope');
INSERT INTO gadget_weapon VALUES (1013, 'Billy Club');
INSERT INTO gadget_weapon VALUES (1013, 'Swing Line');
INSERT INTO gadget_weapon VALUES (1013, 'Cargo Net');
INSERT INTO gadget_weapon VALUES (1013, 'Lift Pole');
INSERT INTO gadget_weapon VALUES (1013, 'Pistol');
INSERT INTO gadget_weapon VALUES (1014, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1014, 'Frisbee Decoy');
INSERT INTO gadget_weapon VALUES (1014, 'Wire Rider');
INSERT INTO gadget_weapon VALUES (1014, 'Blowgun');
INSERT INTO gadget_weapon VALUES (1014, 'Swingline');
INSERT INTO gadget_weapon VALUES (1014, 'Flash Bomb');
INSERT INTO gadget_weapon VALUES (1014, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1014, 'Suitcase Refrigerator');
INSERT INTO gadget_weapon VALUES (1014, 'Portable Optical Scanner');
INSERT INTO gadget_weapon VALUES (1014, 'Nightvision Binoculars');
INSERT INTO gadget_weapon VALUES (1014, 'Plastique w/ Remote Control');
INSERT INTO gadget_weapon VALUES (1014, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1014, 'Rocket Pen');
INSERT INTO gadget_weapon VALUES (1014, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1014, 'Laser Watch');
INSERT INTO gadget_weapon VALUES (1014, 'Tracker-Controlled Shark');
INSERT INTO gadget_weapon VALUES (1014, 'Diving Knife');
INSERT INTO gadget_weapon VALUES (1014, 'High-Powered Telescope');
INSERT INTO gadget_weapon VALUES (1014, 'Cigar Holder');
INSERT INTO gadget_weapon VALUES (1014, 'Torpedo Jet Platform');
INSERT INTO gadget_weapon VALUES (1014, 'Sub-Machine Gun');
INSERT INTO gadget_weapon VALUES (1014, 'Grenades');
INSERT INTO gadget_weapon VALUES (1014, 'Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1015, 'Tracking Devise');
INSERT INTO gadget_weapon VALUES (1015, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1015, 'Grappling Hook');
INSERT INTO gadget_weapon VALUES (1015, 'Flare Gun');
INSERT INTO gadget_weapon VALUES (1015, 'Microcomparitor');
INSERT INTO gadget_weapon VALUES (1015, 'Robotic Surveillance System');
INSERT INTO gadget_weapon VALUES (1015, 'Butterfly Hook');
INSERT INTO gadget_weapon VALUES (1015, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1015, 'Fishing Pole');
INSERT INTO gadget_weapon VALUES (1015, 'Electric Razor Bug Detector');
INSERT INTO gadget_weapon VALUES (1015, 'Mini Cassette Player');
INSERT INTO gadget_weapon VALUES (1015, 'Tint-removing Sunglasses');
INSERT INTO gadget_weapon VALUES (1015, 'Skeleton Key');
INSERT INTO gadget_weapon VALUES (1015, 'Carbon Copying Wallet');
INSERT INTO gadget_weapon VALUES (1015, 'Camera Ring');
INSERT INTO gadget_weapon VALUES (1015, 'Stethascope');
INSERT INTO gadget_weapon VALUES (1015, 'Microchip Hypo');
INSERT INTO gadget_weapon VALUES (1015, 'Hypo Trigger Cane');
INSERT INTO gadget_weapon VALUES (1015, 'Riding Crop');
INSERT INTO gadget_weapon VALUES (1015, 'Garrote');
INSERT INTO gadget_weapon VALUES (1015, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1015, 'Microphone Pole');
INSERT INTO gadget_weapon VALUES (1015, 'Waterproof Tape Recorder');
INSERT INTO gadget_weapon VALUES (1015, 'Timer Mine');
INSERT INTO gadget_weapon VALUES (1015, 'Pistol');
INSERT INTO gadget_weapon VALUES (1015, 'Electric Credit Card Lockpick');
INSERT INTO gadget_weapon VALUES (1015, 'Shotgun');
INSERT INTO gadget_weapon VALUES (1015, 'Chain');
INSERT INTO gadget_weapon VALUES (1015, 'Explosives');
INSERT INTO gadget_weapon VALUES (1015, 'Fire Extinquisher');
INSERT INTO gadget_weapon VALUES (1015, 'Fire Axe');
INSERT INTO gadget_weapon VALUES (1015, 'Flamethrower');
INSERT INTO gadget_weapon VALUES (1016, 'Grappling Hook');
INSERT INTO gadget_weapon VALUES (1016, 'Pistol');
INSERT INTO gadget_weapon VALUES (1016, 'Knife');
INSERT INTO gadget_weapon VALUES (1016, 'Explosives');
INSERT INTO gadget_weapon VALUES (1016, 'Folding Bionoculars');
INSERT INTO gadget_weapon VALUES (1016, 'Stealth Tuxedo');
INSERT INTO gadget_weapon VALUES (1016, 'Sniper Rifle');
INSERT INTO gadget_weapon VALUES (1016, 'Nightvision Binoculars');
INSERT INTO gadget_weapon VALUES (1016, 'Ghetto Blaster');
INSERT INTO gadget_weapon VALUES (1016, 'Headphone Garotte');
INSERT INTO gadget_weapon VALUES (1016, 'Rake Weapon Detector');
INSERT INTO gadget_weapon VALUES (1016, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1016, 'Milk Bomb');
INSERT INTO gadget_weapon VALUES (1016, 'Gas Bomb Key Ring');
INSERT INTO gadget_weapon VALUES (1016, 'Gas Mask');
INSERT INTO gadget_weapon VALUES (1016, 'Skeleton Key');
INSERT INTO gadget_weapon VALUES (1016, 'Body Grab Couch');
INSERT INTO gadget_weapon VALUES (1016, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1016, 'Remote-controlled Camera');
INSERT INTO gadget_weapon VALUES (1016, 'Starlight Scope');
INSERT INTO gadget_weapon VALUES (1016, 'Machine Pistol');
INSERT INTO gadget_weapon VALUES (1016, 'Mini Missles');
INSERT INTO gadget_weapon VALUES (1016, 'Walkman Remote Door Bomb');
INSERT INTO gadget_weapon VALUES (1016, 'Binocular Glasses');
INSERT INTO gadget_weapon VALUES (1016, 'Panic Button Watch');
INSERT INTO gadget_weapon VALUES (1016, 'Bulletproof Vest');
INSERT INTO gadget_weapon VALUES (1016, 'Cloral Hydrate Martini');
INSERT INTO gadget_weapon VALUES (1016, 'Handcuffs');
INSERT INTO gadget_weapon VALUES (1016, 'Billy Club');
INSERT INTO gadget_weapon VALUES (1016, 'Rifle');
INSERT INTO gadget_weapon VALUES (1016, 'Plastique Utility Belt');
INSERT INTO gadget_weapon VALUES (1016, 'Grenade');
INSERT INTO gadget_weapon VALUES (1016, 'Rocket Launcher');
INSERT INTO gadget_weapon VALUES (1016, 'Wire Mic Radio');
INSERT INTO gadget_weapon VALUES (1016, 'Body Armor Machine Gun');
INSERT INTO gadget_weapon VALUES (1016, 'Remote-controlled Cannon');
INSERT INTO gadget_weapon VALUES (1017, '.44 Magnum');
INSERT INTO gadget_weapon VALUES (1017, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1017, 'Polehook');
INSERT INTO gadget_weapon VALUES (1017, 'Manaray Camo Scuba Gear');
INSERT INTO gadget_weapon VALUES (1017, 'Diving Knife');
INSERT INTO gadget_weapon VALUES (1017, 'Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1017, 'Sawed-Off Shotgun');
INSERT INTO gadget_weapon VALUES (1017, 'Swordfish');
INSERT INTO gadget_weapon VALUES (1017, 'Kevlar Vest');
INSERT INTO gadget_weapon VALUES (1017, 'Explosive Alarm Clock');
INSERT INTO gadget_weapon VALUES (1017, 'Dentinite Plastique Toothpaste');
INSERT INTO gadget_weapon VALUES (1017, 'Cigarette Detonator');
INSERT INTO gadget_weapon VALUES (1017, '.220 ID Video Camera Gun');
INSERT INTO gadget_weapon VALUES (1017, 'Camera Sniper Expansion Kit');
INSERT INTO gadget_weapon VALUES (1017, 'Poloroid Laser Gun');
INSERT INTO gadget_weapon VALUES (1017, 'Cummerbund Rope Kit');
INSERT INTO gadget_weapon VALUES (1017, 'Web Netting');
INSERT INTO gadget_weapon VALUES (1017, 'Cyanide Tablet');
INSERT INTO gadget_weapon VALUES (1017, 'Fire Axe');
INSERT INTO gadget_weapon VALUES (1017, 'Broom Radio');
INSERT INTO gadget_weapon VALUES (1017, 'Sub-Machine Gun');
INSERT INTO gadget_weapon VALUES (1017, 'Fire Extinquisher');
INSERT INTO gadget_weapon VALUES (1017, 'Stinger Missles');
INSERT INTO gadget_weapon VALUES (1017, 'Machete');
INSERT INTO gadget_weapon VALUES (1017, 'Lighter');
INSERT INTO gadget_weapon VALUES (1018, 'Grappling Hook Gun');
INSERT INTO gadget_weapon VALUES (1018, 'Lock Decoder');
INSERT INTO gadget_weapon VALUES (1018, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1018, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1018, 'Telescopic Digital Camera');
INSERT INTO gadget_weapon VALUES (1018, 'Goldeneye Orbital Electromagnetic Cannon');
INSERT INTO gadget_weapon VALUES (1018, 'Foot Cast Rocket Launcher');
INSERT INTO gadget_weapon VALUES (1018, 'Repelling Cord Belt');
INSERT INTO gadget_weapon VALUES (1018, 'Phone Booth Airbag Snare');
INSERT INTO gadget_weapon VALUES (1018, 'X-Ray Scanner Tea Tray');
INSERT INTO gadget_weapon VALUES (1018, 'Grenade Pen');
INSERT INTO gadget_weapon VALUES (1018, 'Ejector Desk');
INSERT INTO gadget_weapon VALUES (1018, 'Tranquilizer Dart');
INSERT INTO gadget_weapon VALUES (1018, 'Sub-Machine Gun');
INSERT INTO gadget_weapon VALUES (1018, 'Laser Watch');
INSERT INTO gadget_weapon VALUES (1018, 'Portable Video Monitor');
INSERT INTO gadget_weapon VALUES (1018, 'Remote Detonation Mines');
INSERT INTO gadget_weapon VALUES (1019, 'Zoom Camera w/Satalite Feed');
INSERT INTO gadget_weapon VALUES (1019, 'Lighter Grenade');
INSERT INTO gadget_weapon VALUES (1019, 'Magnetic Grenade');
INSERT INTO gadget_weapon VALUES (1019, 'Submachine Gun');
INSERT INTO gadget_weapon VALUES (1019, 'Stealth Boat');
INSERT INTO gadget_weapon VALUES (1019, 'Sea-Vac Drill Torpedo');
INSERT INTO gadget_weapon VALUES (1019, 'Scrambled Cell Phone');
INSERT INTO gadget_weapon VALUES (1019, 'Multipurpose Cell Phone');
INSERT INTO gadget_weapon VALUES (1019, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1019, 'Repelling Cord Bracelet');
INSERT INTO gadget_weapon VALUES (1019, 'Scuba Gear');
INSERT INTO gadget_weapon VALUES (1019, 'Underwater Flare');
INSERT INTO gadget_weapon VALUES (1019, 'Harpoon Gun');
INSERT INTO gadget_weapon VALUES (1019, 'Handcuffs');
INSERT INTO gadget_weapon VALUES (1019, 'Fisherman Hook');
INSERT INTO gadget_weapon VALUES (1019, 'Steel Clothes Line');
INSERT INTO gadget_weapon VALUES (1019, 'Lockpick Earring');
INSERT INTO gadget_weapon VALUES (1019, 'Bicycle Wheel Frame');
INSERT INTO gadget_weapon VALUES (1019, 'Macroft .59 Pistol');
INSERT INTO gadget_weapon VALUES (1019, 'Remote Detonation Watch');
INSERT INTO gadget_weapon VALUES (1019, 'Dragon Head Flamethrower');
INSERT INTO gadget_weapon VALUES (1019, 'Wiredart Fan');
INSERT INTO gadget_weapon VALUES (1019, 'Bike Part Catapult');
INSERT INTO gadget_weapon VALUES (1019, 'Mines');
INSERT INTO gadget_weapon VALUES (1019, 'Knife');
INSERT INTO gadget_weapon VALUES (1019, 'Nightvision Binoculars');
INSERT INTO gadget_weapon VALUES (1019, 'Grenade');
INSERT INTO gadget_weapon VALUES (1019, 'Throwing Star');
INSERT INTO gadget_weapon VALUES (1019, 'Missles');
INSERT INTO gadget_weapon VALUES (1019, 'Detonators');
INSERT INTO gadget_weapon VALUES (1020, 'Gun Bomb');
INSERT INTO gadget_weapon VALUES (1020, 'Pistol');
INSERT INTO gadget_weapon VALUES (1020, 'Knife');
INSERT INTO gadget_weapon VALUES (1020, 'Extension Cord');
INSERT INTO gadget_weapon VALUES (1020, 'Exploding Money');
INSERT INTO gadget_weapon VALUES (1020, 'Lapel Pin Trigger');
INSERT INTO gadget_weapon VALUES (1020, 'Sniper Machine Gun');
INSERT INTO gadget_weapon VALUES (1020, 'Rocket Launcher');
INSERT INTO gadget_weapon VALUES (1020, 'Bagpipe Machine Gun');
INSERT INTO gadget_weapon VALUES (1020, 'Bubble Jacket');
INSERT INTO gadget_weapon VALUES (1020, 'X-Ray Sunglasses');
INSERT INTO gadget_weapon VALUES (1020, 'Machine Gun');
INSERT INTO gadget_weapon VALUES (1020, 'Lamp Watch');
INSERT INTO gadget_weapon VALUES (1020, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1020, 'Pocket Knife');
INSERT INTO gadget_weapon VALUES (1020, 'Grappling Hook Watch');
INSERT INTO gadget_weapon VALUES (1020, 'Helecoptor Saw');
INSERT INTO gadget_weapon VALUES (1020, 'Crobar');
INSERT INTO gadget_weapon VALUES (1020, 'Plutonium Locator Card');
INSERT INTO gadget_weapon VALUES (1020, 'Briefcase Bomb');
INSERT INTO gadget_weapon VALUES (1020, 'Neck-Breaker Torture Chair');
INSERT INTO gadget_weapon VALUES (1020, 'Cane Gun');
INSERT INTO gadget_weapon VALUES (1020, 'Plutonium Rod');
INSERT INTO gadget_weapon VALUES (1020, 'Heat Signature Satellite');
INSERT INTO gadget_weapon VALUES (1021, 'Surfboard Espionage Kit');
INSERT INTO gadget_weapon VALUES (1021, 'Sub-Machine Gun');
INSERT INTO gadget_weapon VALUES (1021, 'Satalite Beacon Knife');
INSERT INTO gadget_weapon VALUES (1021, 'Walther PPK Handgun');
INSERT INTO gadget_weapon VALUES (1021, 'C-4 Kit w/ Detonator Watch');
INSERT INTO gadget_weapon VALUES (1021, 'Internet Uplink Camera');
INSERT INTO gadget_weapon VALUES (1021, 'Flamethrower');
INSERT INTO gadget_weapon VALUES (1021, 'Tankbuster Rocket Launcher');
INSERT INTO gadget_weapon VALUES (1021, 'Rail Gun');
INSERT INTO gadget_weapon VALUES (1021, 'Binoculars');
INSERT INTO gadget_weapon VALUES (1021, 'Diving Knife');
INSERT INTO gadget_weapon VALUES (1021, 'Switchblade');
INSERT INTO gadget_weapon VALUES (1021, 'Baretta 9 mm w/Silencer');
INSERT INTO gadget_weapon VALUES (1021, 'Plastique Cell Phone Remote');
INSERT INTO gadget_weapon VALUES (1021, 'Oxygen Tank');
INSERT INTO gadget_weapon VALUES (1021, 'Rapier Sword');
INSERT INTO gadget_weapon VALUES (1021, 'Saber Sword');
INSERT INTO gadget_weapon VALUES (1021, 'Katana Long Sword');
INSERT INTO gadget_weapon VALUES (1021, 'Broadsword');
INSERT INTO gadget_weapon VALUES (1021, 'Holographic Training Room');
INSERT INTO gadget_weapon VALUES (1021, 'Suitcase Knife');
INSERT INTO gadget_weapon VALUES (1021, 'Shoe Knife');
INSERT INTO gadget_weapon VALUES (1021, 'Ultrasonic Ring');
INSERT INTO gadget_weapon VALUES (1021, 'Laser Watch');
INSERT INTO gadget_weapon VALUES (1021, 'Icarus Electric Gauntlet');
INSERT INTO gadget_weapon VALUES (1021, 'Window Removal Kit');
INSERT INTO gadget_weapon VALUES (1021, 'Repelling Kit');
INSERT INTO gadget_weapon VALUES (1021, 'Minature Rebreather');
INSERT INTO gadget_weapon VALUES (1021, 'Industrial Laser');
INSERT INTO gadget_weapon VALUES (1021, 'Comb Dagger');
INSERT INTO gadget_weapon VALUES (1021, 'Sniper Rifle');
INSERT INTO gadget_weapon VALUES (1021, 'Icarus Battle Suit');
INSERT INTO gadget_weapon VALUES (1021, 'Throwing Knife');
INSERT INTO gadget_weapon VALUES (1021, 'Katana Short Sword');
INSERT INTO gadget_weapon VALUES (1022, 'Walther P99 Handgun');
INSERT INTO gadget_weapon VALUES (1022, 'Sony Ericsson Cell Phone');
INSERT INTO gadget_weapon VALUES (1022, 'Laptop Computer');
INSERT INTO gadget_weapon VALUES (1022, 'Machete');
INSERT INTO gadget_weapon VALUES (1022, 'Portable Defibrilator');
INSERT INTO gadget_weapon VALUES (1022, 'Universal Poison Antidote Kit');
INSERT INTO gadget_weapon VALUES (1022, 'Subdermal Microtracker');
INSERT INTO gadget_weapon VALUES (1022, 'Miniture Bugging Devise');
INSERT INTO gadget_weapon VALUES (1022, 'Heckler & Koch UMP9 Machine Gun');
INSERT INTO gadget_weapon VALUES (1023, 'Walther P99 Handgun');
INSERT INTO gadget_weapon VALUES (1023, 'Money Tags');
INSERT INTO gadget_weapon VALUES (1023, 'Lockpick');
INSERT INTO gadget_weapon VALUES (1023, 'Switchblade Knife');
INSERT INTO gadget_weapon VALUES (1023, 'Handgun');
INSERT INTO gadget_weapon VALUES (1023, 'Tracker Business Card');
INSERT INTO gadget_weapon VALUES (1023, 'Cellphone w/ GPS Tracking, Camera & Computer Interface');
INSERT INTO gadget_weapon VALUES (1023, 'Sub-machine Gun');
INSERT INTO gadget_weapon VALUES (1023, 'Anchor');
INSERT INTO gadget_weapon VALUES (1023, 'Voice-activated Computer Wall Terminal');
INSERT INTO gadget_weapon VALUES (1023, 'Ear Bud Radio');
INSERT INTO gadget_weapon VALUES (1023, 'Mirror Computer Terminal');
INSERT INTO gadget_weapon VALUES (1023, 'Fire Axe');
